// <auto-generated />
using AISupportAnalysisPlatform.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AISupportAnalysisPlatform.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419071700_AddAnalyticsViews")]
    partial class AddAnalyticsViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AISupportAnalysisPlatform.Models.AI.AgentPerformanceView", b =>
                {
                    b.Property<int?>("AvgResolutionHours").HasColumnType("int");
                    b.Property<string>("AgentEmail").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("AgentName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("AssignedLast7Days").HasColumnType("int");
                    b.Property<int>("CurrentOpenAssigned").HasColumnType("int");
                    b.Property<string>("EntityName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<int>("ResolvedLast30Days").HasColumnType("int");
                    b.Property<int>("SlaBreaches").HasColumnType("int");
                    b.Property<int>("TotalAssigned").HasColumnType("int");
                    b.Property<int>("TotalComments").HasColumnType("int");
                    b.Property<int>("TotalCreated").HasColumnType("int");
                    b.Property<int>("TotalResolved").HasColumnType("int");
                    b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(max)");
                    b.ToView("vw_AgentPerformance");
                });

            modelBuilder.Entity("AISupportAnalysisPlatform.Models.AI.EntityPerformanceView", b =>
                {
                    b.Property<int?>("AvgFirstResponseHours").HasColumnType("int");
                    b.Property<int?>("AvgResolutionHours").HasColumnType("int");
                    b.Property<int>("ClosedTickets").HasColumnType("int");
                    b.Property<int>("EntityId").HasColumnType("int");
                    b.Property<string>("EntityName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("EscalatedTickets").HasColumnType("int");
                    b.Property<DateTime?>("FirstTicketDate").HasColumnType("datetime2");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<DateTime?>("LastTicketDate").HasColumnType("datetime2");
                    b.Property<int>("ManagerReviewCount").HasColumnType("int");
                    b.Property<int>("OpenTickets").HasColumnType("int");
                    b.Property<int>("ResolvedTickets").HasColumnType("int");
                    b.Property<decimal>("SlaBreachRate").HasColumnType("decimal(5,1)");
                    b.Property<int>("SlaBreaches").HasColumnType("int");
                    b.Property<int>("TicketsLast30Days").HasColumnType("int");
                    b.Property<int>("TicketsLast7Days").HasColumnType("int");
                    b.Property<int>("TotalTickets").HasColumnType("int");
                    b.ToView("vw_EntityPerformance");
                });

            modelBuilder.Entity("AISupportAnalysisPlatform.Models.AI.TicketAnalyticsView", b =>
                {
                    b.Property<int>("AffectedUsersCount").HasColumnType("int");
                    b.Property<string>("AssignedToName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("AttachmentCount").HasColumnType("int");
                    b.Property<string>("BrowserName").HasColumnType("nvarchar(max)");
                    b.Property<string>("CategoryName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ClosedAt").HasColumnType("datetime2");
                    b.Property<int>("CommentCount").HasColumnType("int");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("CreatedByName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("DaysOpen").HasColumnType("int");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("DescriptionLength").HasColumnType("int");
                    b.Property<DateTime?>("DueDate").HasColumnType("datetime2");
                    b.Property<string>("EntityName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("EnvironmentName").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("EscalatedAt").HasColumnType("datetime2");
                    b.Property<string>("EscalatedToName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("EscalationLevel").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("FirstRespondedAt").HasColumnType("datetime2");
                    b.Property<int?>("HoursToFirstResponse").HasColumnType("int");
                    b.Property<int?>("HoursToResolution").HasColumnType("int");
                    b.Property<string>("ImpactScope").HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsClosedStatus").HasColumnType("bit");
                    b.Property<bool>("IsSlaBreached").HasColumnType("bit");
                    b.Property<string>("OperatingSystem").HasColumnType("nvarchar(max)");
                    b.Property<int?>("ParentTicketId").HasColumnType("int");
                    b.Property<string>("PendingReason").HasColumnType("nvarchar(max)");
                    b.Property<int>("PriorityLevel").HasColumnType("int");
                    b.Property<string>("PriorityName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("ProductArea").HasColumnType("nvarchar(max)");
                    b.Property<bool>("RequiresManagerReview").HasColumnType("bit");
                    b.Property<string>("ResolutionSummary").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("ResolvedAt").HasColumnType("datetime2");
                    b.Property<string>("ResolvedByName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("RootCause").HasColumnType("nvarchar(max)");
                    b.Property<string>("SourceName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("StatusName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("TicketId").HasColumnType("int");
                    b.Property<string>("TicketNumber").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("TitleLength").HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.ToView("vw_TicketAnalytics");
                });
#pragma warning restore 612, 618
        }
    }
}
